[tool.poetry]
name = "cs-py-intro"
version = "1.0.0"
description = "Python Einführung"
authors = ["Daniel Senften <daniel.senften@talent-factory.ch>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.1.1"
